before_install:
   - sudo apt-get -qq update
   - sudo apt-get install -y graphicsmagick imagemagick
services:
   - mongodb
before_script:
   - npm install
language: node_js
node_js:
     - "6"
     - "6.1"
     - "5.11"
addons:
    code_climate:
     repo_token: 36b731cc971f73c59fd9da3fc753da05168d5ed4c318d335338a901ca8011feb