before_install:
   - sudo apt-get -qq update
   - sudo apt-get install -y graphicsmagick imagemagick
services:
   - mongodb
before_script:
   - npm install
language: node_js
node_js:
     - "6"
     - "6.1"
     - "5.11"
     - "0.6"
     - "iojs"